"""Prompts subpackage."""

from .templates import (
    DECOMPOSITION_SYSTEM,
    EUROVOC_BRIDGE_SYSTEM,
    SUMMARIZATION_SYSTEM,
    SYNTHESIS_SYSTEM,
    VERIFICATION_SYSTEM,
)

__all__ = [
    "DECOMPOSITION_SYSTEM",
    "EUROVOC_BRIDGE_SYSTEM",
    "SUMMARIZATION_SYSTEM",
    "SYNTHESIS_SYSTEM",
    "VERIFICATION_SYSTEM",
]
